"""Transformer-type controller (spec §9): the future joint composition is generated by
*relational reference* to the current materials, the current joint composition, the goal and
the recently realized composition events.

Tokens (§9.1).  Queries are the M track tokens at the current analysis row (track 0 = goal),
each carrying its normalized material feature f_i(t) = unit.f_mat[t, i, :].  Keys/values are

  p = 0            the goal token,          value  xi_G(t) - xi^current
  p = 1 .. M-1     the material tokens,     value  nu_p  = xi^{probe,p}(t) - xi^current
  memory head      the recent events of H,  value  dxi^{event}  (realized composition change)

with xi^{probe,p} = unit.probe(g), g[p] = probe_foreground_gain, all other tracks
probe_background_gain (a probe is analysis material, never an immediate gain command), and
xi^current the running ideal state of the autoregression (initialised from
unit.probe(unit.start_gains)).  The number of tokens therefore depends on M *and* on the
history length; an empty memory attends a single zero-valued current token.

Attention (§9.2, eq. 35):

  A^h_{ip} = softmax_p( S^h_{ip} + B^h_{ip}(H) - M^h_{ip} )
  S^sim_{ip}      = -||f_i - f_p||^2 / (2 sigma_F^2)
  S^contrast_{ip} = +||f_i - f_p||^2 / (2 sigma_F^2)
  S^memory_{ip}   = -||f_i - k_p||^2 / (2 sigma_F^2) - (t - t_p) / tau_H      (k_p = phi-block
                    of the event's xi_end, t_p its end time)
  B(H)            = bias_scale * tanh(corr(M_H)) + bias_scale * tanh(gain * centered(A_EMA))
                    + the bounded provisional bias built inside the unit by update()
  M               = 0 allowed / +inf forbidden; the similarity and contrast heads mask
                    self-reference, every query keeps at least one key.

  O_h = (1/M) sum_i sum_p A^h_{ip} nu_p                                        (eq. 36)

Conditional future of the whole composition (§9.3, eq. 37/38):

  mu_{j+1} = xi_j + o_j (a_s O_sim - a_c O_contrast + a_m O_memory)
                  + a_G (1 - o_j) (xi_G - xi_j)
  Sigma_j  = noise_scale^2 sum_h O_h O_h^T + cov_diag_floor I
  xi_{j+1} = mu_{j+1} + (openness-gated) L eps,  eps time correlated (AR(1)),
             the sampled xi stays the context of the next step; GOAL_HOLD rows are pinned to
             xi_G, and future hypotheses never enter history.events (the engine writes those
             after selection).

Realization (§9.4, eq. 39): E_T = <d_xi^2(xi_t(gamma), xi_hat_t)> over the non-hold rows;
end_unit() writes the attention EMA, the reference order and the chosen realized composition
summary into history.mode_state["transformer"], which is the memory the next unit reads back
(re-openability: the new context is recomputed from eq. 35-38 with those additions).

Not a trained language model: a relational controller over acoustic-composition space
(structure contract T).  Attention weights are never written into gains.
"""
from __future__ import annotations

from typing import Any, Dict, List, Sequence

import numpy as np

from ..types import Candidate, Realization, Target, UnitContext
from .base import ModeController, ar1_noise, fix_hold_rows

_HEADS_FALLBACK = ("similarity", "contrast", "memory")
_HEAD_SIGN = {"similarity": 1.0, "contrast": -1.0, "memory": 1.0}
_HEAD_ALPHA = {"similarity": ("alpha_s", 0.25), "contrast": ("alpha_c", 0.25),
               "memory": ("alpha_m", 0.25)}


def _softmax_masked(logits: np.ndarray, forbidden: np.ndarray) -> np.ndarray:
    """softmax over the last axis; `forbidden` is the +inf mask of eq. (35).

    Any query whose keys are all forbidden falls back to the unmasked row, so every query
    keeps at least one reference target."""
    z = np.where(forbidden, -np.inf, logits)
    empty = ~np.isfinite(z).any(axis=-1)
    if empty.any():
        z = np.where(empty[..., None], logits, z)
        forbidden = forbidden & ~empty[..., None]
    m = np.max(z, axis=-1, keepdims=True)
    m = np.where(np.isfinite(m), m, 0.0)
    e = np.exp(np.clip(z - m, -60.0, 0.0))
    e = np.where(forbidden, 0.0, e)            # forbidden keys get exactly zero weight
    return e / np.maximum(e.sum(axis=-1, keepdims=True), 1e-300)


class TransformerMode(ModeController):
    cli_name = "transformer"
    internal_id = "transformer_relational"

    def __init__(self, cfg, analyzer, fs, rng, objective):
        super().__init__(cfg, analyzer, fs, rng, objective)
        md = cfg.get("mode_defaults", {})
        self.p = dict(md.get("transformer", {}))
        heads = [str(h) for h in md.get("transformer_heads", _HEADS_FALLBACK)]
        known = [h for h in heads if h in _HEAD_SIGN]
        for h in heads:
            if h not in _HEAD_SIGN:
                self.warnings.append(f"transformer: unknown head {h!r} ignored")
        if not known:
            known = list(_HEADS_FALLBACK)
            self.warnings.append("transformer: no known head configured; using similarity/contrast/memory")
        self.heads: List[str] = known
        self.alpha = {h: self._f(*_HEAD_ALPHA[h]) for h in self.heads}
        self.sign = {h: _HEAD_SIGN[h] for h in self.heads}
        self.alpha_G = self._f("alpha_G", 1.0)
        self.sigma_F = max(1e-6, self._f("sigma_F", 1.0))
        self.tau_H = max(1e-6, self._f("tau_H_seconds", 180.0))
        self.bias_scale = self._f("bias_scale", 0.5)
        self.noise_scale = self._f("noise_scale", 0.5)
        self.cov_sd = float(np.sqrt(max(0.0, self._f("cov_diag_floor", 1e-4))))
        self.fg_gain = self._f("probe_foreground_gain", 0.7)
        self.bg_gain = self._f("probe_background_gain", 0.15)
        # local (not in config.py DEFAULTS) knobs, all read with .get(key, default)
        self.stride = max(1, int(self._f("ar_stride", 1.0)))
        self.rho_t = float(np.clip(self._f("time_correlation", 0.9), 0.0, 0.999))
        self.excursion = max(0.05, self._f("excursion_radius", 0.35))
        self.fb_rate = self._f("feedback_rate", 0.5)
        self.fb_bound = max(1e-3, self._f("feedback_bound", 3.0))
        tg = self._f("tendency_gain", 0.0)
        self.tendency_gain = tg if tg > 0 else float(self.M)      # 0 = automatic (= M)
        # explicit physical time scale of one autoregression step (audit §9.3): the increment of
        # eq. (37) is defined per step_seconds_reference seconds and scaled by dt / reference
        self.step_seconds = float(analyzer.hop) / float(fs) * self.stride
        self.step_ref = max(1e-6, self._f("step_seconds_reference", 0.1))
        self.dt_scale = self.step_seconds / self.step_ref
        self.rho = float(cfg["history"]["update_rate"])
        self.max_events = int(cfg["history"]["recent_event_capacity"])
        self.W = analyzer.weight_vector()
        self.attention_traces: List[Dict[str, Any]] = []
        self.memory_traces: List[Dict[str, Any]] = []
        self.weight_traces: List[Dict[str, Any]] = []
        self.A_ema: Dict[str, np.ndarray] = {h: np.zeros((self.M, self.M)) for h in self.heads}
        self.n_events = 0
        self.mu_det_mean = np.zeros(self.d_xi)
        self._saturation_noted = False

    def _f(self, key: str, default: float) -> float:
        return float(self.p.get(key, default))

    # ------------------------------------------------------------------ conditioning (§9.1)
    def begin_unit(self, unit: UnitContext, history) -> None:
        self.unit = unit
        J = unit.J
        st = history.mode_state.get("transformer") or {}
        # --- persisted reference tendencies (part of B(H)) -----------------------------
        self.A_ema = {}
        for h in self.heads:
            v = (st.get("attention_ema") or {}).get(h)
            arr = np.zeros((self.M, self.M))
            if v is not None:
                a = np.asarray(v, dtype=np.float64)
                if a.shape == (self.M, self.M):
                    arr = a
                else:
                    self.warnings.append(f"unit {unit.index}: stored attention EMA for {h} has shape "
                                         f"{a.shape}, expected {(self.M, self.M)}; ignored")
            self.A_ema[h] = arr
        self.persisted_order = [int(x) for x in st.get("reference_order", [])]
        self.persisted_blocks = st.get("chosen_blocks", [])
        self.corr = np.asarray(history.corr(), dtype=np.float64)
        if self.corr.shape != (self.M, self.M):
            self.corr = np.zeros((self.M, self.M))
        # --- memory tokens: recent realized events -------------------------------------
        ev = list(history.events)[-self.max_events:]
        good = [e for e in ev if np.asarray(e.get("xi_end")).shape == (self.d_xi,)
                and np.asarray(e.get("dxi")).shape == (self.d_xi,)]
        if len(good) != len(ev):
            self.warnings.append(f"unit {unit.index}: {len(ev) - len(good)} memory tokens dropped (bad shape)")
        self.events = good
        self.n_events = len(good)
        if good:
            self.ev_key = np.stack([np.asarray(e["xi_end"], dtype=np.float64)[: self.d_phi] for e in good])
            self.ev_val = np.stack([np.asarray(e["dxi"], dtype=np.float64) for e in good])
            self.ev_t = np.array([float(e.get("end_seconds", 0.0)) for e in good])
            self.ev_track = np.array([int(e.get("track", 0)) for e in good])
            self.ev_unit = np.array([int(e.get("unit", -1)) for e in good])
        else:  # empty recollection -> one zero-valued "current" token (§9.2)
            self.ev_key = np.zeros((1, self.d_phi))
            self.ev_val = np.zeros((1, self.d_xi))
            self.ev_t = np.full(1, float(unit.seconds[0]))
            self.ev_track = np.full(1, -1)
            self.ev_unit = np.full(1, -1)
        # --- key vectors: goal token + one foreground probe per material ---------------
        self.xi_key = np.zeros((J, self.M, self.d_xi))
        self.xi_key[:, 0, :] = unit.xi_goal
        self.probe_gains: List[List[float]] = []
        for i in range(1, self.M):
            g = np.full(self.M, self.bg_gain)
            g[i] = self.fg_gain
            xi_p, _ = unit.probe(g)
            self.xi_key[:, i, :] = xi_p
            self.probe_gains.append([float(x) for x in g])
        xi_start, _ = unit.probe(unit.start_gains)
        self.xi_start = xi_start[0].copy()
        # --- autoregression grid (coarse; mu is linearly interpolated back to J rows) ---
        rows = np.arange(0, J, self.stride, dtype=np.int64)
        if rows.size == 0:
            rows = np.array([0], dtype=np.int64)
        if rows[-1] != J - 1:
            rows = np.append(rows, J - 1)
        self.rows = rows
        S = len(rows)
        f = unit.f_mat[rows]                                        # (S, M, d_phi)
        diff = f[:, :, None, :] - f[:, None, :, :]
        self.D2 = (diff ** 2).sum(axis=-1)                          # (S, M, M)
        dm = f[:, :, None, :] - self.ev_key[None, None, :, :]
        self.D2m = (dm ** 2).sum(axis=-1)                           # (S, M, K)
        self.recency = np.maximum(unit.seconds[rows][:, None, None] - self.ev_t[None, None, :], 0.0) / self.tau_H
        self.mask_pair = np.broadcast_to(np.eye(self.M, dtype=bool), (S, self.M, self.M))
        self.mask_mem = np.zeros((S, self.M, self.ev_key.shape[0]), dtype=bool)
        # --- bounded excursion region for the generated ideal state --------------------
        # Eq. (37) has the fixed point xi* = xi_G + [o/(1-o)] (attention displacement): xi_G
        # anchors the closed side and the openness factor is what diverges at o = 1, where
        # the restoring term vanishes entirely.  The anchor therefore slides from the goal
        # composition (o = 0) to the centroid of the reference tokens (o = 1), and the
        # excursion around it is saturated at excursion_radius * o_j * max_p d_xi(key_p, mean).
        key_mean = self.xi_key.mean(axis=1)                          # (J, d)
        o_col = unit.o[:, None]
        self.xi_ref = (1.0 - o_col) * unit.xi_goal + o_col * key_mean
        d2p = self.analyzer.dist2(self.xi_key[rows], key_mean[rows][:, None, :])      # (S, M)
        self.rad2 = np.maximum((self.excursion * unit.o[rows]) ** 2 * d2p.max(axis=1), 1e-12)
        # --- provisional (within-unit) bias, reset each unit ---------------------------
        self.fb_pair_raw = np.zeros(self.M)
        self.fb_mem_raw = np.zeros(self.ev_key.shape[0])
        self.fb_pair = np.zeros(self.M)
        self.fb_mem = np.zeros(self.ev_key.shape[0])
        self.fb_rounds = 0
        self._att = None
        self.att0 = self._attention()
        self._att = self.att0
        # deterministic (zero-noise) mu path, used by signature() and by update()
        coarse, n_clip = self._ar_path(self.att0, None)
        self.mu_det_coarse = coarse
        mu_det = fix_hold_rows(unit, self._interp(coarse))
        self.mu_det = mu_det
        fm = unit.free_mask
        self.mu_det_mean = mu_det[fm].mean(axis=0) if fm.any() else mu_det.mean(axis=0)
        # re-openability (§9.4): the composition that reached the goal last time, carried onto
        # this unit's grid, against the context eq. (35)-(38) has just regenerated
        reopen = None
        if self.persisted_blocks:
            try:
                past = {k: np.asarray(v, dtype=np.float64)
                        for k, v in self.persisted_blocks[-1]["blocks"].items()}
                reopen = float(unit.mean_dist2(self.objective.blocks_to_unit(unit, past), mu_det))
            except Exception as e:  # noqa: BLE001
                self.warnings.append(f"unit {unit.index}: stored composition blocks unusable ({e})")
        self.attention_traces.append({
            "unit": int(unit.index), "grid_rows": int(J), "autoregression_steps": int(S),
            "memory_tokens": int(self.n_events), "openness_mean_free": float(unit.mean_openness),
            "mean_attention": {h: self.att0[h]["A_mean"].tolist() for h in self.heads},
            "persisted_reference_order": list(self.persisted_order),
            "persisted_blocks_units": [int(b.get("unit", -1)) for b in self.persisted_blocks],
            "reopen_context_dist2_to_new_ideal": reopen,
            "deterministic_mu_clipped_steps": int(n_clip),
            "bound_usage_rate": float(n_clip) / float(max(1, len(self.rows))),
            "bound_definition": "radial tanh squash of (mu - xi_ref) at radius excursion_radius * o_j * "
                                "max_p d_xi(key_p, key centroid); direction from xi_ref preserved, "
                                "xi_ref = (1 - o) xi_G + o * key centroid",
            "time_scale": {"hop_seconds": float(self.analyzer.hop) / float(self.fs), "ar_stride": int(self.stride),
                           "step_seconds": self.step_seconds, "step_seconds_reference": self.step_ref,
                           "dt_scale": self.dt_scale},
        })
        if n_clip > 0.5 * S and not self._saturation_noted:
            self._saturation_noted = True
            self.warnings.append(
                "transformer: with alpha_s = alpha_c the two material heads of eq. (37) are a pure "
                "translation and the restoring term vanishes at o = 1, so the ideal trajectory runs "
                "into the bounded excursion radius (unit %d: %d/%d autoregression steps); the "
                "attention still fixes the direction of the excursion, its magnitude is saturated"
                % (unit.index, n_clip, S))

    # ------------------------------------------------------------------ attention (eq. 35/36)
    def _bias_tendency(self, h: str) -> np.ndarray:
        """Bounded bias from the persisted mean attention of head h (row-centered, so an
        absent / uniform tendency contributes exactly zero)."""
        A = self.A_ema.get(h)
        if A is None:
            return np.zeros((self.M, self.M))
        dev = A - A.mean(axis=1, keepdims=True)
        return self.bias_scale * np.tanh(self.tendency_gain * dev)

    def _attention(self) -> Dict[str, Dict[str, Any]]:
        """All heads at once on the coarse rows, including the value-side context of eq. (36)."""
        S = len(self.rows)
        out: Dict[str, Dict[str, Any]] = {}
        B_corr = self.bias_scale * np.tanh(self.corr)
        score_pair = self.D2 / (2.0 * self.sigma_F ** 2)
        for h in self.heads:
            if h == "memory":
                B = B_corr[:, self.ev_track.clip(0, self.M - 1)]                   # (M, K)
                B = np.where(self.ev_track[None, :] >= 0, B, 0.0)
                tend = self._bias_tendency("memory")
                Bt = tend[:, self.ev_track.clip(0, self.M - 1)]
                B = B + np.where(self.ev_track[None, :] >= 0, Bt, 0.0)
                logits = (-self.D2m / (2.0 * self.sigma_F ** 2) - self.recency
                          + B[None, :, :] + self.fb_mem[None, None, :])
                A = _softmax_masked(logits, self.mask_mem)                          # (S, M, K)
                base = np.einsum("sip,pd->sd", A, self.ev_val) / float(self.M)
                A_mean = A.mean(axis=0)
                by_track = np.zeros((self.M, self.M))
                for k, tr in enumerate(self.ev_track):
                    if 0 <= tr < self.M:
                        by_track[:, tr] += A_mean[:, k]
                out[h] = {"A": A, "A_mean": A_mean, "by_track": by_track, "base": base,
                          "relative": False}
            else:
                s = -score_pair if h == "similarity" else score_pair
                B = B_corr + self._bias_tendency(h)
                logits = s + B[None, :, :] + (self.sign[h] * self.fb_pair)[None, None, :]
                A = _softmax_masked(logits, self.mask_pair)                         # (S, M, M)
                base = np.einsum("sip,spd->sd", A, self.xi_key[self.rows]) / float(self.M)
                A_mean = A.mean(axis=0)
                out[h] = {"A": A, "A_mean": A_mean, "by_track": A_mean, "base": base,
                          "relative": True}
        return out

    def _bound(self, mu: np.ndarray, s: int):
        """Bounded excursion of the generated ideal state.

        With alpha_s = alpha_c the two material heads of eq. (37) contribute a pure
        translation alpha (Ctx_sim - Ctx_contrast), and the only restoring term,
        alpha_G (1 - o)(xi_G - xi), vanishes exactly where o = 1 (the OPEN phase), so the
        recursion is a drifting random walk there.  The excursion around the openness
        anchor xi_ref is therefore squashed smoothly (tanh: identity to first order,
        saturating at the radius) into the ball of radius
        excursion_radius * o_j * max_p d_xi(key_p, key centroid)."""
        ref = self.xi_ref[self.rows[s]]
        d = mu - ref
        d2 = float(self.analyzer.dist2(d, np.zeros(self.d_xi)))
        if d2 <= 1e-300:
            return mu, False
        r = float(np.sqrt(self.rad2[s]))
        rho = float(np.sqrt(d2))
        scale = r * np.tanh(rho / r) / rho
        return ref + d * scale, bool(rho > r)

    # ------------------------------------------------------------------ eq. (37)/(38)
    def _ar_path(self, att: Dict[str, Dict[str, Any]], eps):
        """One conditional future: xi_hat_1..xi_hat_S on the coarse grid (the sampled state is
        the context of the next step).  eps=None gives the deterministic mean path."""
        unit = self.unit
        rows = self.rows
        S = len(rows)
        nh = len(self.heads)
        xi = self.xi_start.copy()
        out = np.zeros((S, self.d_xi))
        n_clip = 0
        for s in range(S):
            j = int(rows[s])
            o = float(unit.o[j])
            O = []
            step = np.zeros(self.d_xi)
            for h in self.heads:
                Oh = att[h]["base"][s] - xi if att[h]["relative"] else att[h]["base"][s]
                O.append(Oh)
                step = step + self.sign[h] * self.alpha[h] * Oh
            mu = xi + self.dt_scale * (o * step + self.alpha_G * (1.0 - o) * (unit.xi_goal[j] - xi))
            if eps is not None:
                u = eps[s]
                fl = np.zeros(self.d_xi)
                for k in range(nh):
                    fl = fl + float(u[k]) * O[k]
                fl = self.noise_scale * fl + self.cov_sd * u[nh:]
                mu = mu + np.sqrt(self.dt_scale) * o * fl   # openness-gated fluctuation, per sqrt(dt)
            mu, clipped = self._bound(mu, s)
            n_clip += int(clipped)
            if unit.hold_mask[j]:
                mu = unit.xi_goal[j].copy()
            out[s] = mu
            xi = mu
        return out, n_clip

    def _interp(self, coarse: np.ndarray) -> np.ndarray:
        J = self.unit.J
        if len(self.rows) == J:
            return coarse
        x = np.arange(J, dtype=np.float64)
        xp = self.rows.astype(np.float64)
        out = np.empty((J, self.d_xi))
        for d in range(self.d_xi):
            out[:, d] = np.interp(x, xp, coarse[:, d])
        return out

    # ------------------------------------------------------------------ hints
    def hints(self, unit: UnitContext, history) -> List[tuple]:
        out: List[tuple] = []
        seen = set()

        def add(a: int, b: int, rel: str) -> None:
            key = (min(a, b), max(a, b), rel)
            if a != b and key not in seen:
                seen.add(key)
                out.append((int(a), int(b), rel))

        if self.M < 3:
            return out
        for h, rel, n in (("similarity", "sync", 2), ("contrast", "counter", 1)):
            if h not in self.att0:
                continue
            sub = np.array(self.att0[h]["A_mean"][1:, 1:], dtype=np.float64)
            if sub.size == 0:
                continue
            np.fill_diagonal(sub, -np.inf)
            taken = 0
            for flat in np.argsort(-sub, axis=None):
                a, b = np.unravel_index(int(flat), sub.shape)
                before = len(seen)
                add(int(a) + 1, int(b) + 1, rel)
                taken += int(len(seen) > before)
                if taken >= n:
                    break
        return out

    # ------------------------------------------------------------------ proposals (eq. 38)
    def propose(self, unit: UnitContext, history, round_index: int, n_targets: int) -> List[Target]:
        att = self._att if self._att is not None else self._attention()
        self._att = att
        mem = att.get("memory")
        ev_w = mem["A_mean"].mean(axis=0) if mem is not None else None
        targets: List[Target] = []
        S = len(self.rows)
        nd = len(self.heads) + self.d_xi
        for a in range(n_targets):
            eps = ar1_noise(self.rng, S, nd, self.rho_t)
            coarse, n_clip = self._ar_path(att, eps)
            xi_hat = fix_hold_rows(unit, self._interp(coarse))
            meta = {
                "round": int(round_index),
                "attention_mean": {h: att[h]["A_mean"].tolist() for h in self.heads},
                "attention_by_track": {h: att[h]["by_track"].tolist() for h in self.heads},
                "memory_reference_weights": (ev_w.tolist() if ev_w is not None else []),
                "memory_tokens": int(self.n_events),
                "excursion_clipped_steps": int(n_clip),
                "provisional_bias": self.fb_pair.tolist(),
                "mean_free_state": (xi_hat[unit.free_mask].mean(axis=0).tolist()
                                    if unit.free_mask.any() else xi_hat.mean(axis=0).tolist()),
            }
            targets.append(Target(f"transformer:u{unit.index}:r{round_index}:{a}", xi_hat, meta=meta))
        return targets

    # ------------------------------------------------------------------ eq. (39)
    def mode_error(self, unit: UnitContext, cand: Candidate, target: Target) -> float:
        """E_T(gamma; Xi_hat) = <d_xi^2(xi_t(gamma), xi_hat_t)> over the non-hold rows."""
        return float(unit.mean_dist2(cand.xi, target.xi_hat))

    # ------------------------------------------------------------------ within-unit update
    def _wcos(self, a: np.ndarray, b: np.ndarray) -> float:
        na = float(np.sqrt(max(1e-300, (a * a * self.W).sum())))
        nb = float(np.sqrt(max(1e-300, (b * b * self.W).sum())))
        return float((a * b * self.W).sum() / (na * nb + 1e-12))

    def update(self, unit: UnitContext, history, realizations: Sequence[Realization],
               round_index: int) -> Dict[str, Any]:
        """Provisional context from this round's *realized* compositions: the realized change
        per phase block is compared with each reference's value direction and the temporary
        (tanh-bounded) attention bias moves toward the references that explain it better.
        Never writes to history.events - the engine does that after selection."""
        if not realizations:
            return {}
        totals = np.array([float(r.total) for r in realizations])
        tau = max(1e-9, self.objective.selection_temperature(unit.mean_openness))
        w = np.exp(-(totals - totals.min()) / tau)
        w = w / max(w.sum(), 1e-300)
        dxi = np.zeros(self.d_xi)
        n_blocks = 0
        for wr, r in zip(w, realizations):
            blocks = self.objective.phase_blocks(unit, r.candidate.xi)
            if not blocks:
                continue
            d = np.mean([blocks[s][-1] - blocks[s][0] for s in blocks], axis=0)
            dxi = dxi + float(wr) * d
            n_blocks += len(blocks)
        if n_blocks == 0 or not np.isfinite(dxi).all():
            return {"skipped": "no phase blocks"}
        nu_bar = (self.xi_key[self.rows] - self.mu_det_coarse[:, None, :]).mean(axis=0)   # (M, d)
        align = np.array([self._wcos(nu_bar[p], dxi) for p in range(self.M)])
        align_m = np.array([self._wcos(self.ev_val[k], dxi) for k in range(self.ev_val.shape[0])])
        if self.n_events == 0:
            align_m = np.zeros_like(align_m)
        self.fb_pair_raw = np.clip(self.fb_pair_raw + self.fb_rate * align,
                                   -self.fb_bound, self.fb_bound)
        self.fb_mem_raw = np.clip(self.fb_mem_raw + self.fb_rate * align_m,
                                  -self.fb_bound, self.fb_bound)
        self.fb_pair = self.bias_scale * np.tanh(self.fb_pair_raw)
        self.fb_mem = self.bias_scale * np.tanh(self.fb_mem_raw)
        self.fb_rounds += 1
        self._att = self._attention()     # the next round proposes from the updated references
        return {"round": int(round_index), "realized_change_norm": float(np.sqrt((dxi * dxi * self.W).sum())),
                "key_alignment": [float(x) for x in align],
                "provisional_bias": [float(x) for x in self.fb_pair],
                "memory_alignment_max": float(np.max(np.abs(align_m))) if align_m.size else 0.0,
                "realizations": int(len(realizations))}

    # ------------------------------------------------------------------ memory write (eq. 27)
    def end_unit(self, unit: UnitContext, history, chosen: Realization, alternatives) -> None:
        meta = dict(chosen.target.meta or {})
        by_track = meta.get("attention_by_track", {})
        st = dict(history.mode_state.get("transformer") or {})
        ema = dict(st.get("attention_ema") or {})
        for h in self.heads:
            cur = np.asarray(by_track.get(h, np.zeros((self.M, self.M))), dtype=np.float64)
            if cur.shape != (self.M, self.M):
                cur = np.zeros((self.M, self.M))
            prev = np.asarray(ema.get(h, self.A_ema[h]), dtype=np.float64)
            if prev.shape != (self.M, self.M):
                prev = np.zeros((self.M, self.M))
            ema[h] = ((1.0 - self.rho) * prev + self.rho * cur).tolist()
        ref_head = "similarity" if "similarity" in self.heads else self.heads[0]
        mass = np.asarray(ema[ref_head], dtype=np.float64).sum(axis=0)
        order = [int(i) for i in np.argsort(-mass)]
        blocks = self.objective.phase_blocks(unit, chosen.candidate.xi)
        st["attention_ema"] = ema
        st["reference_order"] = order
        st["reference_mass"] = [float(x) for x in mass]
        st["n_memory_tokens"] = int(self.n_events)
        hist_blocks = list(st.get("chosen_blocks") or [])
        hist_blocks.append({"unit": int(unit.index),
                            "blocks": {k: v.tolist() for k, v in blocks.items()}})
        st["chosen_blocks"] = hist_blocks[-2:]
        history.mode_state["transformer"] = st
        # --- traces ---------------------------------------------------------------------
        mem_refs: List[Dict[str, Any]] = []
        ev_w = meta.get("memory_reference_weights") or []
        if self.n_events and ev_w:
            top = np.argsort(-np.asarray(ev_w, dtype=np.float64))[:6]
            for k in top:
                k = int(k)
                mem_refs.append({"event_unit": int(self.ev_unit[k]), "track": int(self.ev_track[k]),
                                 "end_seconds": float(self.ev_t[k]), "weight": float(ev_w[k]),
                                 "recency_seconds": float(unit.seconds[-1] - self.ev_t[k])})
        self.memory_traces.append({"unit": int(unit.index), "memory_tokens": int(self.n_events),
                                   "references": mem_refs})
        pool = [chosen] + [x for x in alternatives]
        totals = np.array([float(x.total) for x in pool])
        tau = self.objective.selection_temperature(unit.mean_openness)
        z = -(totals - totals.min()) / max(tau, 1e-12)
        wsel = np.exp(z - z.max())
        wsel = wsel / wsel.sum()
        order_w = np.argsort(-wsel)[:8]
        self.weight_traces.append({
            "unit": int(unit.index), "selection_temperature": float(tau),
            "entries": [{"candidate_id": int(pool[int(k)].candidate.id),
                         "target_id": pool[int(k)].target.id,
                         "total": float(totals[int(k)]), "softmax_weight": float(wsel[int(k)]),
                         "chosen": bool(int(k) == 0)} for k in order_w]})
        self.unit_traces.append({
            "unit": int(unit.index), "chosen_target": chosen.target.id,
            "normalized_mode_error": float(chosen.normalized_mode_error),
            "memory_tokens": int(self.n_events), "feedback_rounds": int(self.fb_rounds),
            "provisional_bias": [float(x) for x in self.fb_pair],
            "reference_order_after": order,
            "probe_gains": self.probe_gains,
            "excursion_clipped_steps": int(meta.get("excursion_clipped_steps", 0)),
        })

    # ------------------------------------------------------------------ signature / trace
    def signature(self) -> np.ndarray:
        parts = [np.asarray(self.A_ema[h], dtype=np.float64).ravel() for h in self.heads]
        parts.append(np.array([float(self.n_events)]))
        parts.append(np.asarray(self.mu_det_mean, dtype=np.float64))
        return np.concatenate(parts)

    def trace(self) -> Dict[str, Any]:
        return {
            "token_definition": {
                "queries": "M track tokens at the current row (track 0 = goal), feature f_i(t)",
                "keys_values": "goal token (xi_G - xi_current), material probes (nu_p), memory events (dxi)",
                "probe_gains": "foreground %.3f / background %.3f" % (self.fg_gain, self.bg_gain),
                "heads": list(self.heads),
                "coefficients": {"alpha": {h: self.alpha[h] for h in self.heads},
                                 "sign": {h: self.sign[h] for h in self.heads},
                                 "alpha_G": self.alpha_G, "sigma_F": self.sigma_F,
                                 "tau_H_seconds": self.tau_H, "bias_scale": self.bias_scale,
                                 "noise_scale": self.noise_scale, "cov_diag_floor": self.cov_sd ** 2},
                "autoregression": {"stride_rows": self.stride, "time_correlation": self.rho_t,
                                   "excursion_radius": self.excursion},
            },
            "attention_summary": self.attention_traces,
            "memory_references": self.memory_traces,
            "candidate_weights": self.weight_traces,
            "warnings": list(self.warnings),
            "units": self.unit_traces,
        }
