"""Transformer-type controller (spec §9; audit-2 §B5/B6/C4/C7/D3): the future joint composition is
generated by *relational reference* to the current materials, the realized current composition, the
goal and the committed composition events of the history.

Tokens (§9.1).  Queries are the M track tokens at the current analysis row (track 0 = goal),
each carrying its normalized material feature f_i(t) = unit.f_mat[t, i, :].  Keys/values are

  p = 0            the goal token,          value  xi_G(t) - xi^current
  p = 1 .. M-1     the material tokens,     value  nu_p  = xi^{probe,p}(t) - xi^current
  memory head      committed events of H,   value  dxi^{event}  (realized composition change)
                   + a small per-track long-term digest of committed events (audit C7: a short
                     recent list plus a small long-term summary, kept in history.mode_state)

with xi^{probe,p} = unit.probe(g), g[p] = probe_foreground_gain, all other tracks
probe_background_gain (a probe is analysis material, never an immediate gain command), and
xi^current the running ideal state of the autoregression.  The number of tokens therefore depends
on M *and* on the committed history; an empty recollection attends a single zero-valued token.

Attention (§9.2, eq. 35):

  A^h_{ip} = softmax_p( S^h_{ip} + B^h_{ip}(H) - M^h_{ip} )
  S^sim_{ip}      = -||f_i - f_p||^2 / (2 sigma_F^2)
  S^contrast_{ip} = +||f_i - f_p||^2 / (2 sigma_F^2)
  S^memory_{ip}   = -||f_i - k_p||^2 / (2 sigma_F^2) - (t - t_p) / tau_H      (k_p = phi-block
                    of the event's xi_end, t_p its end time)
  B(H)            = bias_scale * tanh(corr(M_H)) + bias_scale * tanh(gain * centered(A_EMA))
                    both read from the COMMITTED history only (history.corr(),
                    history.mode_state["transformer"]["attention_ema"])
  M               = 0 allowed / +inf forbidden; the similarity and contrast heads mask
                    self-reference, every query keeps at least one key.

  O_h = (1/M) sum_i sum_p A^h_{ip} nu_p                                        (eq. 36)

Conditional future of the whole composition (§9.3, eq. 37/38), run on the MODEL step:

  mu_{j+1} = xi_j + (dt/dt_ref) [ o_j (a_s O_sim - a_c O_contrast + a_m O_memory)
                                  + a_G (1 - o_j) (xi_G - xi_j) ]
  Sigma_j  = noise_scale^2 sum_h O_h O_h^T + cov_diag_floor I
  xi_{j+1} = mu_{j+1} + sqrt(dt/dt_ref) o_j L eps,  eps AR(1) with rho = exp(-dt_model/tau_noise),
             followed by the bounded radial tanh excursion (once per model step); the sampled xi
             stays the context of the next step; GOAL_HOLD rows are pinned to xi_G and future
             hypotheses never enter history.events (the engine writes committed events itself).

Audit-2 changes (B5/C4/D3):

* `prepare_reference(unit, history, rows, xi_current, n)` builds the reference for the next
  lookahead window only, starting from the REALIZED current composition `xi_current` (not from the
  unit-start silence/goal probe), with the memory head attending the committed events available at
  that moment and B(H) from the committed history.  The engine freezes one of the returned
  proposals; it never moves while the gain trajectory is improved against it.
* the within-unit feedback bias that adapted the reference toward realized candidates is removed
  (`update()` is not called any more and is not implemented here).
* `observe_committed(...)` is the only learning step: the attention actually used for the committed
  block updates the attention EMA / reference order and the long-term memory digest with the
  history rate rho = 1 - exp(-dt / tau_H), persisted JSON-able in history.mode_state["transformer"].
* three time scales are separated (B6/D3.4): the analysis hop, the model step
  (`analysis.model_step_seconds`, stride = round(model_step / hop) >= 1) and the AR correlation
  time `tau_noise_seconds` (rho = exp(-model_step / tau_noise)).  Changing the analysis hop alone
  does not change the expressed dynamics (trace field `time_scale`).

Realization (§9.4, eq. 39): E_T = <d_xi^2(xi_t(gamma), xi_hat_t)> over the non-hold rows (the
window restriction of the same quantity is the default `window_error`).

Not a trained language model: a relational controller over acoustic-composition space
(structure contract T).  Attention weights are never written into gains.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

import numpy as np

from ..types import Candidate, Realization, Target, UnitContext
from .base import ModeController, ar1_noise, ar1_rho_for, fix_hold_rows

_HEADS_FALLBACK = ("similarity", "contrast", "memory")
_HEAD_SIGN = {"similarity": 1.0, "contrast": -1.0, "memory": 1.0}
_HEAD_ALPHA = {"similarity": ("alpha_s", 0.25), "contrast": ("alpha_c", 0.25),
               "memory": ("alpha_m", 0.25)}
_EV_KEY = ("end_frame", "start_frame", "track")


def _softmax_masked(logits: np.ndarray, forbidden: np.ndarray) -> np.ndarray:
    """softmax over the last axis; `forbidden` is the +inf mask of eq. (35).

    Any query whose keys are all forbidden falls back to the unmasked row, so every query
    keeps at least one reference target."""
    z = np.where(forbidden, -np.inf, logits)
    empty = ~np.isfinite(z).any(axis=-1)
    if empty.any():
        z = np.where(empty[..., None], logits, z)
        forbidden = forbidden & ~empty[..., None]
    m = np.max(z, axis=-1, keepdims=True)
    m = np.where(np.isfinite(m), m, 0.0)
    e = np.exp(np.clip(z - m, -60.0, 0.0))
    e = np.where(forbidden, 0.0, e)            # forbidden keys get exactly zero weight
    return e / np.maximum(e.sum(axis=-1, keepdims=True), 1e-300)


def _event_key(e: Dict[str, Any]) -> tuple:
    return tuple(int(e.get(k, -1)) for k in _EV_KEY)


class TransformerMode(ModeController):
    cli_name = "transformer"
    internal_id = "transformer_relational"

    def __init__(self, cfg, analyzer, fs, rng, objective):
        super().__init__(cfg, analyzer, fs, rng, objective)
        md = cfg.get("mode_defaults", {})
        self.p = dict(md.get("transformer", {}))
        heads = [str(h) for h in md.get("transformer_heads", _HEADS_FALLBACK)]
        known = [h for h in heads if h in _HEAD_SIGN]
        for h in heads:
            if h not in _HEAD_SIGN:
                self.warnings.append(f"transformer: unknown head {h!r} ignored")
        if not known:
            known = list(_HEADS_FALLBACK)
            self.warnings.append("transformer: no known head configured; using similarity/contrast/memory")
        self.heads: List[str] = known
        self.alpha = {h: self._f(*_HEAD_ALPHA[h]) for h in self.heads}
        self.sign = {h: _HEAD_SIGN[h] for h in self.heads}
        self.alpha_G = self._f("alpha_G", 1.0)
        self.sigma_F = max(1e-6, self._f("sigma_F", 1.0))
        self.tau_H = max(1e-6, self._f("tau_H_seconds", 180.0))
        self.bias_scale = self._f("bias_scale", 0.5)
        self.noise_scale = self._f("noise_scale", 0.5)
        self.cov_sd = float(np.sqrt(max(0.0, self._f("cov_diag_floor", 1e-4))))
        self.fg_gain = self._f("probe_foreground_gain", 0.7)
        self.bg_gain = self._f("probe_background_gain", 0.15)
        self.excursion = max(0.05, self._f("excursion_radius", 0.35))
        tg = self._f("tendency_gain", 0.0)
        self.tendency_gain = tg if tg > 0 else float(self.M)      # 0 = automatic (= M)
        # ---- three separated time scales (audit B6 / D3.4) ------------------------------
        # analysis hop: observation grid; model step: one autoregression step; tau_noise: the
        # correlation time of the driving noise.  The autoregression runs on the model step and is
        # interpolated to the analysis rows, so changing the hop alone does not change the dynamics.
        self.hop_s = float(analyzer.hop) / float(fs)
        self.model_step_cfg = float(cfg["analysis"].get("model_step_seconds", self.hop_s))
        self.stride = max(1, int(round(self.model_step_cfg / max(1e-9, self.hop_s))))
        self.model_step = self.stride * self.hop_s
        if abs(self.model_step - self.model_step_cfg) > 0.25 * max(1e-9, self.model_step_cfg):
            self.warnings.append(
                "transformer: analysis.model_step_seconds %.4f s is not representable on the analysis hop "
                "%.4f s; the autoregression runs at %.4f s (stride %d)"
                % (self.model_step_cfg, self.hop_s, self.model_step, self.stride))
        if abs(self._f("ar_stride", 1.0) - 1.0) > 1e-9:
            self.warnings.append("transformer: mode_defaults.transformer.ar_stride is superseded by "
                                 "analysis.model_step_seconds (audit B6/D3.4) and is ignored")
        # AR(1) correlation time of the noise: the legacy coefficient `time_correlation` is read as
        # rho at 0.1 s, so tau_noise defaults to ~0.949 s (= the old 0.9 at a 0.1 s step).
        tc = float(np.clip(self._f("time_correlation", 0.9), 1e-6, 0.999))
        self.tau_noise = max(1e-6, float(self.p.get("tau_noise_seconds", -0.1 / float(np.log(tc)))))
        self.rho_t = float(np.clip(ar1_rho_for(self.model_step, self.tau_noise), 0.0, 0.999999))
        # the increment of eq. (37) is defined per step_seconds_reference seconds (dt scaling kept)
        self.step_ref = max(1e-6, self._f("step_seconds_reference", 0.1))
        self.dt_scale = self.model_step / self.step_ref
        self.ignored_parameters = ["feedback_rate", "feedback_bound (within-unit reference feedback "
                                   "removed, audit B5/C4/D3.3)", "ar_stride (-> analysis.model_step_seconds)"]
        self.rho = float(cfg["history"]["update_rate"])
        self.max_events = int(cfg["history"]["recent_event_capacity"])
        _ds = int(self.p.get("memory_digest_slots", 0))
        self.digest_slots = _ds if _ds > 0 else self.M          # 0 = automatic: one slot per track
        self.attention_traces: List[Dict[str, Any]] = []
        self.memory_traces: List[Dict[str, Any]] = []
        self.weight_traces: List[Dict[str, Any]] = []
        self.A_ema: Dict[str, np.ndarray] = {h: np.zeros((self.M, self.M)) for h in self.heads}
        self.n_events = 0
        self.mu_det_mean = np.zeros(self.d_xi)
        self._last_event_key: tuple = (-1, -1, -1)
        self._saturation_noted = False
        self._max_step_traces = 2000

    def _f(self, key: str, default: float) -> float:
        return float(self.p.get(key, default))

    # ================================================================== committed history
    def _history_pack(self, unit: UnitContext, history, empty: bool = False,
                      warn: bool = False) -> Dict[str, Any]:
        """Everything eq. (35)-(36) takes from the COMMITTED history: the bias B(H) (correlation of
        M_H and the persisted attention EMA) and the memory tokens (recent committed events plus the
        bounded long-term digest).  `empty=True` builds the same structure from no history at all
        (used by the window-level history-intervention probe, audit D3.6)."""
        M, d, dphi = self.M, self.d_xi, self.d_phi
        A: Dict[str, np.ndarray] = {h: np.zeros((M, M)) for h in self.heads}
        corr = np.zeros((M, M))
        ev: List[Dict[str, Any]] = []
        digest: List[Dict[str, Any]] = []
        if not empty and history is not None:
            c = np.asarray(history.corr(), dtype=np.float64)
            if c.shape == (M, M) and np.isfinite(c).all():
                corr = c
            st = history.mode_state.get("transformer") or {}
            stored = st.get("attention_ema") or {}
            for h in self.heads:
                v = stored.get(h)
                if v is None:
                    continue                       # no committed attention yet -> zero tendency
                a = np.asarray(v, dtype=np.float64)
                if a.shape == (M, M) and np.isfinite(a).all():
                    A[h] = a
                elif warn:
                    self.warnings.append(f"unit {unit.index}: stored attention EMA for {h} has shape "
                                         f"{a.shape}, expected {(M, M)}; ignored")
            raw = list(history.events)[-self.max_events:]
            ev = [e for e in raw if np.asarray(e.get("xi_end")).shape == (d,)
                  and np.asarray(e.get("dxi")).shape == (d,)]
            if warn and len(ev) != len(raw):
                self.warnings.append(f"unit {unit.index}: {len(raw) - len(ev)} memory tokens dropped (bad shape)")
            for slot in (st.get("memory_digest") or []):
                try:
                    k = np.asarray(slot["key"], dtype=np.float64)
                    v = np.asarray(slot["value"], dtype=np.float64)
                    if k.shape == (dphi,) and v.shape == (d,) and np.isfinite(k).all() and np.isfinite(v).all():
                        digest.append({"key": k, "value": v, "t": float(slot.get("t_seconds", 0.0)),
                                       "track": int(slot.get("track", -1)), "unit": int(slot.get("unit", -1)),
                                       "count": int(slot.get("count", 0))})
                except Exception:  # noqa: BLE001
                    continue
        keys = [np.asarray(e["xi_end"], dtype=np.float64)[:dphi] for e in ev]
        vals = [np.asarray(e["dxi"], dtype=np.float64) for e in ev]
        ts = [float(e.get("end_seconds", 0.0)) for e in ev]
        tracks = [int(e.get("track", -1)) for e in ev]
        units = [int(e.get("unit", -1)) for e in ev]
        kinds = ["recent"] * len(ev)
        for slot in digest:
            keys.append(slot["key"])
            vals.append(slot["value"])
            ts.append(slot["t"])
            tracks.append(slot["track"])
            units.append(slot["unit"])
            kinds.append("digest")
        n_real = len(keys)
        if n_real == 0:                                  # empty recollection -> one zero token (§9.2)
            keys, vals = [np.zeros(dphi)], [np.zeros(d)]
            ts, tracks, units, kinds = [float(unit.seconds[0])], [-1], [-1], ["empty"]
        return {"corr": corr, "A": A,
                "ev_key": np.stack(keys), "ev_val": np.stack(vals), "ev_t": np.asarray(ts, dtype=np.float64),
                "ev_track": np.asarray(tracks, dtype=np.int64), "ev_unit": np.asarray(units, dtype=np.int64),
                "ev_kind": kinds, "n_recent": len(ev), "n_digest": len(digest), "n_tokens": n_real,
                "source": "empty_history" if empty else "committed_history",
                "history_version": 0 if (empty or history is None) else int(history.n_updates)}

    # ================================================================== context / attention
    def _coarse_rows(self, rows: np.ndarray) -> np.ndarray:
        """Model-step rows inside `rows` (audit D3.4: the autoregression runs on the model step)."""
        r = np.asarray(rows, dtype=np.int64)
        if r.size == 0:
            return r
        sel = r[:: self.stride]
        if sel.size == 0:
            sel = r[:1]
        if int(sel[-1]) != int(r[-1]):
            sel = np.append(sel, r[-1])
        return sel

    def _context(self, unit: UnitContext, crows: np.ndarray, xi_start: np.ndarray,
                 pack: Dict[str, Any]) -> Dict[str, Any]:
        """Scores of eq. (35) on the model-step rows `crows` for one history pack and start state."""
        S = int(len(crows))
        K = int(pack["ev_key"].shape[0])
        f = unit.f_mat[crows]                                        # (S, M, d_phi)
        diff = f[:, :, None, :] - f[:, None, :, :]
        dm = f[:, :, None, :] - pack["ev_key"][None, None, :, :]
        return {
            "rows": crows, "S": S, "xi_start": np.asarray(xi_start, dtype=np.float64).copy(),
            "D2": (diff ** 2).sum(axis=-1),                          # (S, M, M)
            "D2m": (dm ** 2).sum(axis=-1),                           # (S, M, K)
            "recency": np.maximum(unit.seconds[crows][:, None, None] - pack["ev_t"][None, None, :], 0.0) / self.tau_H,
            "mask_pair": np.broadcast_to(np.eye(self.M, dtype=bool), (S, self.M, self.M)),
            "mask_mem": np.zeros((S, self.M, K), dtype=bool),
            "xi_key": self.xi_key[crows], "pack": pack,
        }

    def _bias_tendency(self, pack: Dict[str, Any], h: str) -> np.ndarray:
        """Bounded bias from the committed attention EMA of head h (row-centered, so an absent /
        uniform tendency contributes exactly zero)."""
        A = pack["A"].get(h)
        if A is None:
            return np.zeros((self.M, self.M))
        dev = A - A.mean(axis=1, keepdims=True)
        return self.bias_scale * np.tanh(self.tendency_gain * dev)

    def _attention(self, ctx: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
        """All heads at once on the model-step rows, including the value-side context of eq. (36)."""
        pack = ctx["pack"]
        ev_track = pack["ev_track"]
        out: Dict[str, Dict[str, Any]] = {}
        B_corr = self.bias_scale * np.tanh(pack["corr"])
        score_pair = ctx["D2"] / (2.0 * self.sigma_F ** 2)
        for h in self.heads:
            if h == "memory":
                B = B_corr[:, ev_track.clip(0, self.M - 1)]                       # (M, K)
                B = np.where(ev_track[None, :] >= 0, B, 0.0)
                tend = self._bias_tendency(pack, "memory")
                Bt = tend[:, ev_track.clip(0, self.M - 1)]
                B = B + np.where(ev_track[None, :] >= 0, Bt, 0.0)
                logits = -ctx["D2m"] / (2.0 * self.sigma_F ** 2) - ctx["recency"] + B[None, :, :]
                A = _softmax_masked(logits, ctx["mask_mem"])                      # (S, M, K)
                base = np.einsum("sip,pd->sd", A, pack["ev_val"]) / float(self.M)
                A_mean = A.mean(axis=0)
                by_track = np.zeros((self.M, self.M))
                for k, tr in enumerate(ev_track):
                    if 0 <= tr < self.M:
                        by_track[:, tr] += A_mean[:, k]
                out[h] = {"A_mean": A_mean, "by_track": by_track, "base": base, "relative": False}
            else:
                s = -score_pair if h == "similarity" else score_pair
                B = B_corr + self._bias_tendency(pack, h)
                logits = s + B[None, :, :]
                A = _softmax_masked(logits, ctx["mask_pair"])                     # (S, M, M)
                base = np.einsum("sip,spd->sd", A, ctx["xi_key"]) / float(self.M)
                A_mean = A.mean(axis=0)
                out[h] = {"A_mean": A_mean, "by_track": A_mean, "base": base, "relative": True}
        return out

    # ================================================================== eq. (37)/(38)
    def _bound(self, mu: np.ndarray, j: int):
        """Bounded excursion of the generated ideal state, applied once per MODEL step.

        With alpha_s = alpha_c the two material heads of eq. (37) contribute a pure translation
        alpha (Ctx_sim - Ctx_contrast), and the only restoring term, alpha_G (1 - o)(xi_G - xi),
        vanishes exactly where o = 1 (the OPEN phase), so the recursion is a drifting random walk
        there.  The excursion around the openness anchor xi_ref is therefore squashed smoothly
        (tanh: identity to first order, saturating at the radius) into the ball of radius
        excursion_radius * o_j * max_p d_xi(key_p, key centroid)."""
        ref = self.xi_ref[j]
        d = mu - ref
        d2 = float(self.analyzer.dist2(d, np.zeros(self.d_xi)))
        if d2 <= 1e-300:
            return mu, False
        r = float(np.sqrt(self.rad2_all[j]))
        rho = float(np.sqrt(d2))
        scale = r * np.tanh(rho / r) / rho
        return ref + d * scale, bool(rho > r)

    def _ar_path(self, ctx: Dict[str, Any], att: Dict[str, Dict[str, Any]], eps):
        """One conditional future on the model-step grid of `ctx` (the sampled state is the context
        of the next step).  eps=None gives the deterministic mean path."""
        unit = self.unit
        rows = ctx["rows"]
        nh = len(self.heads)
        xi = ctx["xi_start"].copy()
        out = np.zeros((ctx["S"], self.d_xi))
        n_clip = 0
        for s in range(ctx["S"]):
            j = int(rows[s])
            o = float(unit.o[j])
            O = []
            step = np.zeros(self.d_xi)
            for h in self.heads:
                Oh = att[h]["base"][s] - xi if att[h]["relative"] else att[h]["base"][s]
                O.append(Oh)
                step = step + self.sign[h] * self.alpha[h] * Oh
            mu = xi + self.dt_scale * (o * step + self.alpha_G * (1.0 - o) * (unit.xi_goal[j] - xi))
            if eps is not None:
                u = eps[s]
                fl = np.zeros(self.d_xi)
                for k in range(nh):
                    fl = fl + float(u[k]) * O[k]
                fl = self.noise_scale * fl + self.cov_sd * u[nh:]
                mu = mu + np.sqrt(self.dt_scale) * o * fl   # openness-gated fluctuation, per sqrt(dt)
            mu, clipped = self._bound(mu, j)
            n_clip += int(clipped)
            if unit.hold_mask[j]:
                mu = unit.xi_goal[j].copy()
            out[s] = mu
            xi = mu
        return out, n_clip

    def _interp(self, coarse: np.ndarray, crows: np.ndarray, rows: np.ndarray) -> np.ndarray:
        """Model-step path -> analysis rows (the only place the hop enters the dynamics)."""
        rows = np.asarray(rows, dtype=np.int64)
        crows = np.asarray(crows, dtype=np.int64)
        if crows.shape == rows.shape and np.array_equal(crows, rows):
            return coarse
        x = rows.astype(np.float64)
        xp = crows.astype(np.float64)
        out = np.empty((len(rows), self.d_xi))
        for d in range(self.d_xi):
            out[:, d] = np.interp(x, xp, coarse[:, d])
        return out

    def _att_meta(self, att: Dict[str, Dict[str, Any]], pack: Dict[str, Any]) -> Dict[str, Any]:
        mem = att.get("memory")
        ev_w = mem["A_mean"].mean(axis=0) if mem is not None else None
        return {
            "attention_by_track": {h: att[h]["by_track"].tolist() for h in self.heads},
            "memory_reference_weights": (ev_w.tolist() if ev_w is not None else []),
            "memory_tokens": [{"unit": int(pack["ev_unit"][k]), "track": int(pack["ev_track"][k]),
                               "end_seconds": float(pack["ev_t"][k]), "kind": pack["ev_kind"][k]}
                              for k in range(int(pack["ev_key"].shape[0]))],
            "memory_token_counts": {"recent": int(pack["n_recent"]), "digest": int(pack["n_digest"])},
            "history_version": int(pack["history_version"]),
        }

    # ================================================================== conditioning (§9.1)
    def begin_unit(self, unit: UnitContext, history) -> None:
        self.unit = unit
        J = unit.J
        pack0 = self._history_pack(unit, history, warn=True)
        self.A_ema = {h: np.array(pack0["A"][h], dtype=np.float64, copy=True) for h in self.heads}
        self.n_events = int(pack0["n_tokens"]) if pack0["ev_kind"][0] != "empty" else 0
        st = history.mode_state.get("transformer") or {}
        self.persisted_order = [int(x) for x in st.get("reference_order", [])]
        self.persisted_blocks = st.get("chosen_blocks", [])
        # --- key vectors: goal token + one foreground probe per material ---------------
        self.xi_key = np.zeros((J, self.M, self.d_xi))
        self.xi_key[:, 0, :] = unit.xi_goal
        self.probe_gains: List[List[float]] = []
        for i in range(1, self.M):
            g = np.full(self.M, self.bg_gain)
            g[i] = self.fg_gain
            xi_p, _ = unit.probe(g)
            self.xi_key[:, i, :] = xi_p
            self.probe_gains.append([float(x) for x in g])
        xi_start, _ = unit.probe(unit.start_gains)
        self.xi_start = xi_start[0].copy()
        # --- bounded excursion region for the generated ideal state (all rows) ---------
        # Eq. (37) has the fixed point xi* = xi_G + [o/(1-o)] (attention displacement): xi_G anchors
        # the closed side and the openness factor is what diverges at o = 1, where the restoring
        # term vanishes entirely.  The anchor therefore slides from the goal composition (o = 0) to
        # the centroid of the reference tokens (o = 1).
        key_mean = self.xi_key.mean(axis=1)                          # (J, d)
        o_col = unit.o[:, None]
        self.xi_ref = (1.0 - o_col) * unit.xi_goal + o_col * key_mean
        d2p = self.analyzer.dist2(self.xi_key, key_mean[:, None, :])                 # (J, M)
        self.rad2_all = np.maximum((self.excursion * unit.o) ** 2 * d2p.max(axis=1), 1e-12)
        # --- unit-level (warm start) context on the model-step grid --------------------
        self.crows_unit = self._coarse_rows(np.arange(J, dtype=np.int64))
        self.ctx_unit = self._context(unit, self.crows_unit, self.xi_start, pack0)
        self.att0 = self._attention(self.ctx_unit)
        coarse, n_clip = self._ar_path(self.ctx_unit, self.att0, None)
        self.mu_det = fix_hold_rows(unit, self._interp(coarse, self.crows_unit, np.arange(J, dtype=np.int64)))
        fm = unit.free_mask
        self.mu_det_mean = self.mu_det[fm].mean(axis=0) if fm.any() else self.mu_det.mean(axis=0)
        # --- per-unit accumulators (commit level) --------------------------------------
        self._unit_commits = 0
        self._unit_mem_acc: Dict[tuple, Dict[str, Any]] = {}
        self._unit_bound_clipped = 0
        self._unit_bound_steps = 0
        self._unit_window_refs = 0
        self._win_probe: Optional[Dict[str, Any]] = None
        self._xi_current_warned = False
        # re-openability (§9.4): the composition that reached the goal last time, carried onto this
        # unit's grid, against the context eq. (35)-(38) has just regenerated
        reopen = None
        if self.persisted_blocks:
            try:
                past = {k: np.asarray(v, dtype=np.float64)
                        for k, v in self.persisted_blocks[-1]["blocks"].items()}
                reopen = float(unit.mean_dist2(self.objective.blocks_to_unit(unit, past), self.mu_det))
            except Exception as e:  # noqa: BLE001
                self.warnings.append(f"unit {unit.index}: stored composition blocks unusable ({e})")
        S = int(self.ctx_unit["S"])
        self.attention_traces.append({
            "unit": int(unit.index), "grid_rows": int(J), "autoregression_steps": S,
            "memory_tokens": int(self.n_events),
            "memory_token_counts": {"recent": int(pack0["n_recent"]), "digest": int(pack0["n_digest"])},
            "openness_mean_free": float(unit.mean_openness),
            "mean_attention_at_unit_start": {h: self.att0[h]["A_mean"].tolist() for h in self.heads},
            "attention_ema_used": {h: pack0["A"][h].tolist() for h in self.heads},
            "history_correlation_used": pack0["corr"].tolist(),
            "persisted_reference_order": list(self.persisted_order),
            "persisted_blocks_units": [int(b.get("unit", -1)) for b in self.persisted_blocks],
            "reopen_context_dist2_to_new_ideal": reopen,
            "deterministic_mu_clipped_steps": int(n_clip),
            "bound_usage_rate_unit_path": float(n_clip) / float(max(1, S)),
            "bound_definition": "radial tanh squash of (mu - xi_ref) at radius excursion_radius * o_j * "
                                "max_p d_xi(key_p, key centroid), applied once per model step; direction "
                                "from xi_ref preserved, xi_ref = (1 - o) xi_G + o * key centroid",
            "time_scale": self._time_scale(),
        })
        if n_clip > 0.5 * S and not self._saturation_noted:
            self._saturation_noted = True
            self.warnings.append(
                "transformer: with alpha_s = alpha_c the two material heads of eq. (37) are a pure "
                "translation and the restoring term vanishes at o = 1, so the ideal trajectory runs "
                "into the bounded excursion radius (unit %d: %d/%d model steps); the attention still "
                "fixes the direction of the excursion, its magnitude is saturated"
                % (unit.index, n_clip, S))

    def _time_scale(self) -> Dict[str, Any]:
        return {
            "analysis_hop_seconds": self.hop_s,
            "model_step_seconds_config": self.model_step_cfg,
            "model_step_seconds_effective": self.model_step,
            "stride_analysis_rows": int(self.stride),
            "step_seconds_reference": self.step_ref,
            "dt_scale": self.dt_scale,
            "tau_noise_seconds": self.tau_noise,
            "ar_noise_rho": self.rho_t,
            "tau_memory_seconds": self.tau_H,
            "history_rate": "attention EMA / memory digest use rho = 1 - exp(-dt_commit / tau_H) of the history",
            "hop_invariance": "every constant of the dynamics is defined in seconds, not in analysis rows: the "
                              "autoregression runs on the model step (stride = round(model_step / hop) >= 1) and is "
                              "interpolated to the analysis rows, rho_noise = exp(-model_step / tau_noise), the "
                              "increment is scaled by model_step / step_seconds_reference and the radial bound is "
                              "applied once per model step.  Halving analysis.hop_seconds therefore leaves "
                              "model_step_seconds_effective, ar_noise_rho, dt_scale and the bounding cadence "
                              "unchanged (only `stride` doubles).  What still changes with the hop is the OBSERVED "
                              "composition itself (STFT window centers): on the fixture, halving the hop moves the "
                              "goal composition xi_G by more, in the same metric, than it moves this mode's ideal "
                              "path - that residual belongs to the analysis layer, not to the mode's dynamics.",
            "hop_invariance_before_audit": "the previous version stepped once per analysis row with a fixed "
                                           "per-row rho (0.9) and dt_scale = hop / step_seconds_reference, so "
                                           "halving the hop halved the increment per row and doubled the noise "
                                           "correlation time in seconds",
            "bounding": "radial tanh excursion applied once per model step",
        }

    # ================================================================== hints
    def hints(self, unit: UnitContext, history) -> List[tuple]:
        out: List[tuple] = []
        seen = set()

        def add(a: int, b: int, rel: str) -> None:
            key = (min(a, b), max(a, b), rel)
            if a != b and key not in seen:
                seen.add(key)
                out.append((int(a), int(b), rel))

        if self.M < 3:
            return out
        for h, rel, n in (("similarity", "sync", 2), ("contrast", "counter", 1)):
            if h not in self.att0:
                continue
            sub = np.array(self.att0[h]["A_mean"][1:, 1:], dtype=np.float64)
            if sub.size == 0:
                continue
            np.fill_diagonal(sub, -np.inf)
            taken = 0
            for flat in np.argsort(-sub, axis=None):
                a, b = np.unravel_index(int(flat), sub.shape)
                before = len(seen)
                add(int(a) + 1, int(b) + 1, rel)
                taken += int(len(seen) > before)
                if taken >= n:
                    break
        return out

    # ================================================================== warm start (eq. 38)
    def propose(self, unit: UnitContext, history, round_index: int, n_targets: int) -> List[Target]:
        """Full-unit ideal trajectories from the unit start (used only for the legal warm start)."""
        att = self.att0
        pack = self.ctx_unit["pack"]
        meta0 = self._att_meta(att, pack)
        all_rows = np.arange(unit.J, dtype=np.int64)
        targets: List[Target] = []
        nd = len(self.heads) + self.d_xi
        for a in range(int(n_targets)):
            eps = ar1_noise(self.rng, int(self.ctx_unit["S"]), nd, self.rho_t)
            coarse, n_clip = self._ar_path(self.ctx_unit, att, eps)
            xi_hat = fix_hold_rows(unit, self._interp(coarse, self.crows_unit, all_rows))
            meta = dict(meta0)
            meta.update({
                "scope": "unit", "round": int(round_index),
                "start_from": "unit_start_probe(unit.start_gains)",
                "model_steps": int(self.ctx_unit["S"]),
                "excursion_clipped_steps": int(n_clip),
                "bound_usage_rate": float(n_clip) / float(max(1, int(self.ctx_unit["S"]))),
                "mean_free_state": (xi_hat[unit.free_mask].mean(axis=0).tolist()
                                    if unit.free_mask.any() else xi_hat.mean(axis=0).tolist()),
            })
            targets.append(Target(f"transformer:u{unit.index}:r{round_index}:{a}", xi_hat, meta=meta))
        return targets

    # ================================================================== window reference (audit C4/D3.1)
    def prepare_reference(self, unit: UnitContext, history, rows: np.ndarray, xi_current: np.ndarray,
                          n_proposals: int) -> List[Target]:
        """Ideal trajectories for the next lookahead window only.

        The autoregression is restarted from the REALIZED current composition `xi_current` (the last
        committed row), runs on the model-step subset of `rows`, and reads the committed history as
        it stands now (bias B(H), attention EMA, committed events + long-term digest).  Rows outside
        the window are filled with the unit-level ideal path; GOAL_HOLD rows are pinned to xi_goal.
        Hypotheses stay inside the proposal: nothing is written to history.events here."""
        rows = np.asarray(rows, dtype=np.int64)
        if rows.size == 0:
            return self.propose(unit, history, 0, n_proposals)
        xi0 = np.asarray(xi_current, dtype=np.float64).reshape(-1)
        if xi0.shape != (self.d_xi,) or not np.isfinite(xi0).all():
            if not self._xi_current_warned:
                self._xi_current_warned = True
                self.warnings.append(f"unit {unit.index}: realized current composition unusable "
                                     f"(shape {np.shape(xi_current)}); window reference restarted from "
                                     f"the unit-start probe")
            xi0 = self.xi_start.copy()
        pack = self._history_pack(unit, history)
        crows = self._coarse_rows(rows)
        ctx = self._context(unit, crows, xi0, pack)
        att = self._attention(ctx)
        # audit D3.6: once per unit, how much the committed history moves the frozen window reference
        if self._win_probe is None and int(getattr(history, "n_updates", 0)) > 0:
            self._win_probe = self._window_history_probe(unit, ctx, att, rows, crows, xi0, pack)
        meta0 = self._att_meta(att, pack)
        nd = len(self.heads) + self.d_xi
        fm_w = unit.free_mask[rows]
        out: List[Target] = []
        for a in range(max(1, int(n_proposals))):
            eps = ar1_noise(self.rng, int(ctx["S"]), nd, self.rho_t)
            coarse, n_clip = self._ar_path(ctx, att, eps)
            xi_hat = self.mu_det.copy()                     # unit-level path outside the window
            xi_hat[rows] = self._interp(coarse, crows, rows)
            xi_hat = fix_hold_rows(unit, xi_hat)
            meta = dict(meta0)
            meta.update({
                "scope": "window", "start_from": "realized_current_composition",
                "window_rows": [int(rows[0]), int(rows[-1])],
                "window_seconds": [float(unit.seconds[rows[0]]), float(unit.seconds[rows[-1]])],
                "model_steps": int(ctx["S"]),
                "excursion_clipped_steps": int(n_clip),
                "bound_usage_rate": float(n_clip) / float(max(1, int(ctx["S"]))),
                "mean_free_state": (xi_hat[rows][fm_w].mean(axis=0).tolist() if fm_w.any()
                                    else xi_hat[rows].mean(axis=0).tolist()),
            })
            out.append(Target(f"transformer:u{unit.index}:w{int(rows[0])}:{a}", xi_hat, meta=meta))
            self._unit_bound_clipped += int(n_clip)
            self._unit_bound_steps += int(ctx["S"])
            self._unit_window_refs += 1
        return out

    def _window_history_probe(self, unit: UnitContext, ctx: Dict[str, Any], att: Dict[str, Dict[str, Any]],
                              rows: np.ndarray, crows: np.ndarray, xi0: np.ndarray,
                              pack: Dict[str, Any]) -> Dict[str, Any]:
        """Window-level history intervention (audit D3.6, bounded: one extra deterministic path per
        unit): the same frozen window reference built from the committed history and from an empty
        history, with everything else (unit, rows, realized start state, rng) identical."""
        a, _ = self._ar_path(ctx, att, None)
        pack_e = self._history_pack(unit, None, empty=True)
        ctx_e = self._context(unit, crows, xi0, pack_e)
        b, _ = self._ar_path(ctx_e, self._attention(ctx_e), None)
        ra = self._interp(a, crows, rows)
        rb = self._interp(b, crows, rows)
        return {
            "unit": int(unit.index), "window_rows": [int(rows[0]), int(rows[-1])],
            "model_steps": int(len(crows)), "history_version": int(pack["history_version"]),
            "memory_tokens_committed": int(pack["n_tokens"]),
            "reference_difference_norm": float(np.linalg.norm(ra - rb)),
            "reference_difference_mean_dist2": float(self.analyzer.dist2(ra, rb).mean()),
            "definition": "||xi_hat(committed history) - xi_hat(empty history)|| on the window rows, "
                          "deterministic (zero-noise) path, first commit step of the unit",
        }

    # ================================================================== eq. (39)
    def mode_error(self, unit: UnitContext, cand: Candidate, target: Target) -> float:
        """E_T(gamma; Xi_hat) = <d_xi^2(xi_t(gamma), xi_hat_t)> over the non-hold rows."""
        return float(unit.mean_dist2(cand.xi, target.xi_hat))

    # ================================================================== committed learning (audit C7/D3)
    def observe_committed(self, unit: UnitContext, history, rows: np.ndarray, xi_rows: np.ndarray,
                          parts_rows: Dict[str, np.ndarray], reference: Optional[Target],
                          stats: Dict[str, Any]) -> Dict[str, Any]:
        """The only learning step of this mode: the attention that produced the frozen reference of
        the committed block updates the attention EMA / reference order, the newly committed events
        update the bounded long-term memory digest, and both are persisted JSON-able in
        history.mode_state["transformer"]."""
        rows = np.asarray(rows, dtype=np.int64)
        dt = float(len(rows)) * self.hop_s
        rho = float(history.rho_dt(dt))
        meta = dict((reference.meta if reference is not None else {}) or {})
        by = meta.get("attention_by_track") or {}
        st = dict(history.mode_state.get("transformer") or {})
        ema = dict(st.get("attention_ema") or {})
        updated = []
        for h in self.heads:
            cur = np.asarray(by.get(h, np.zeros((self.M, self.M))), dtype=np.float64)
            if cur.shape != (self.M, self.M) or not np.isfinite(cur).all():
                cur = np.zeros((self.M, self.M))
            else:
                updated.append(h)
            prev = np.asarray(ema.get(h, self.A_ema[h]), dtype=np.float64)
            if prev.shape != (self.M, self.M) or not np.isfinite(prev).all():
                prev = np.zeros((self.M, self.M))
            new = (1.0 - rho) * prev + rho * cur
            self.A_ema[h] = new
            ema[h] = new.tolist()
        st["attention_ema"] = ema
        mass = np.asarray(self.A_ema[self._ref_head()], dtype=np.float64).sum(axis=0)
        st["reference_order"] = [int(i) for i in np.argsort(-mass)]
        st["reference_mass"] = [float(x) for x in mass]
        # --- long-term memory digest (audit C7: short recent list + small long-term summary) ---
        n_new = self._update_digest(st, history, rho)
        st["n_memory_tokens"] = int(len(meta.get("memory_tokens") or []))
        st["last_commit"] = {"unit": int(unit.index), "rows": int(len(rows)), "dt_seconds": dt, "rho": rho,
                             "reference_hash": stats.get("reference_hash"),
                             "reference_id": (reference.id if reference is not None else None)}
        history.mode_state["transformer"] = st
        # --- memory references actually used by that reference --------------------------
        top = self._record_memory_use(meta)
        fitd = None
        if reference is not None:
            fmw = unit.free_mask[rows]
            d = self.analyzer.dist2(np.asarray(xi_rows, dtype=np.float64), reference.xi_hat[rows])
            fitd = float(d[fmw].mean()) if fmw.any() else float(d.mean())
        self._unit_commits += 1
        rec = {
            "unit": int(unit.index), "commit": int(self._unit_commits),
            "t_seconds": float(unit.seconds[rows[0]]), "dt_seconds": dt, "history_rho": rho,
            "reference_scope": meta.get("scope", "unit"),
            "reference_id": (reference.id if reference is not None else None),
            "reference_hash": stats.get("reference_hash"),
            "memory_tokens": meta.get("memory_token_counts", {}),
            "new_committed_events_digested": int(n_new),
            "bound_usage_rate": float(meta.get("bound_usage_rate", 0.0)),
            "committed_fit_dist2": fitd,
            "top_memory_reference": top,
            "reference_order_after": st["reference_order"],
        }
        if len(self.step_traces) < self._max_step_traces:
            self.step_traces.append(rec)
        return {"rho": rho, "dt_seconds": dt, "heads_updated": updated,
                "memory_tokens": int(len(meta.get("memory_tokens") or [])),
                "new_committed_events_digested": int(n_new),
                "bound_usage_rate": float(meta.get("bound_usage_rate", 0.0)),
                "committed_fit_dist2": fitd, "top_memory_reference": top,
                "reference_scope": meta.get("scope", "unit")}

    def _ref_head(self) -> str:
        return "similarity" if "similarity" in self.heads else self.heads[0]

    def _update_digest(self, st: Dict[str, Any], history, rho: float) -> int:
        """Fold the events committed since the last call into one EMA slot per track (bounded)."""
        new = [e for e in history.events if _event_key(e) > self._last_event_key]
        if not new:
            return 0
        self._last_event_key = _event_key(new[-1])
        slots: Dict[int, Dict[str, Any]] = {}
        for slot in (st.get("memory_digest") or []):
            try:
                slots[int(slot["track"])] = dict(slot)
            except Exception:  # noqa: BLE001
                continue
        n_ok = 0
        for e in new:
            k = np.asarray(e.get("xi_end"), dtype=np.float64)
            v = np.asarray(e.get("dxi"), dtype=np.float64)
            if k.shape != (self.d_xi,) or v.shape != (self.d_xi,):
                continue
            k = k[: self.d_phi]
            tr = int(e.get("track", -1))
            cur = slots.get(tr)
            if cur is None:
                cur = {"track": tr, "key": k.tolist(), "value": v.tolist(), "count": 0,
                       "t_seconds": float(e.get("end_seconds", 0.0)), "unit": int(e.get("unit", -1))}
            else:
                pk = np.asarray(cur["key"], dtype=np.float64)
                pv = np.asarray(cur["value"], dtype=np.float64)
                if pk.shape != (self.d_phi,) or pv.shape != (self.d_xi,):
                    pk, pv = k, v
                cur["key"] = ((1.0 - rho) * pk + rho * k).tolist()
                cur["value"] = ((1.0 - rho) * pv + rho * v).tolist()
                cur["t_seconds"] = float(e.get("end_seconds", cur["t_seconds"]))
                cur["unit"] = int(e.get("unit", cur.get("unit", -1)))
            cur["count"] = int(cur.get("count", 0)) + 1
            slots[tr] = cur
            n_ok += 1
        keep = sorted(slots.values(), key=lambda s: -float(s.get("t_seconds", 0.0)))[: self.digest_slots]
        st["memory_digest"] = keep
        return n_ok

    def _record_memory_use(self, meta: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Accumulate which memory references the committed block's reference actually attended."""
        w = np.asarray(meta.get("memory_reference_weights") or [], dtype=np.float64)
        toks = meta.get("memory_tokens") or []
        if w.size == 0 or w.size != len(toks):
            return None
        top: Optional[Dict[str, Any]] = None
        order = np.argsort(-w)
        for rank, k in enumerate(order[:3]):
            k = int(k)
            t = toks[k]
            if int(t.get("track", -1)) < 0:         # placeholder token of an empty recollection
                continue
            key = (int(t.get("unit", -1)), int(t.get("track", -1)), round(float(t.get("end_seconds", 0.0)), 3),
                   str(t.get("kind", "recent")))
            acc = self._unit_mem_acc.setdefault(key, {
                "event_unit": key[0], "track": key[1], "end_seconds": key[2], "kind": key[3],
                "weight_sum": 0.0, "max_weight": 0.0, "commits": 0})
            acc["weight_sum"] += float(w[k])
            acc["max_weight"] = max(acc["max_weight"], float(w[k]))
            acc["commits"] += 1
            if top is None:
                top = {"event_unit": key[0], "track": key[1], "end_seconds": key[2], "kind": key[3],
                       "weight": float(w[k])}
        return top

    # ================================================================== memory write (eq. 27)
    def end_unit(self, unit: UnitContext, history, chosen: Realization, alternatives) -> None:
        st = dict(history.mode_state.get("transformer") or {})
        if self._unit_commits == 0:
            # no commit step ran (degenerate unit): fall back to the unit reference's attention
            meta = dict(chosen.target.meta or {})
            by = meta.get("attention_by_track", {})
            ema = dict(st.get("attention_ema") or {})
            for h in self.heads:
                cur = np.asarray(by.get(h, np.zeros((self.M, self.M))), dtype=np.float64)
                if cur.shape != (self.M, self.M):
                    cur = np.zeros((self.M, self.M))
                prev = np.asarray(ema.get(h, self.A_ema[h]), dtype=np.float64)
                if prev.shape != (self.M, self.M):
                    prev = np.zeros((self.M, self.M))
                self.A_ema[h] = (1.0 - self.rho) * prev + self.rho * cur
                ema[h] = self.A_ema[h].tolist()
            st["attention_ema"] = ema
            self._record_memory_use(meta)
        mass = np.asarray(self.A_ema[self._ref_head()], dtype=np.float64).sum(axis=0)
        order = [int(i) for i in np.argsort(-mass)]
        st["reference_order"] = order
        st["reference_mass"] = [float(x) for x in mass]
        st["n_memory_tokens"] = int(self.n_events)
        blocks = self.objective.phase_blocks(unit, chosen.candidate.xi)
        hist_blocks = list(st.get("chosen_blocks") or [])
        hist_blocks.append({"unit": int(unit.index), "blocks": {k: v.tolist() for k, v in blocks.items()}})
        st["chosen_blocks"] = hist_blocks[-2:]
        history.mode_state["transformer"] = st
        # --- traces ---------------------------------------------------------------------
        refs = sorted(self._unit_mem_acc.values(), key=lambda a: -a["weight_sum"])[:6]
        for a in refs:
            a["mean_weight"] = float(a["weight_sum"]) / float(max(1, a["commits"]))
            a["recency_seconds_at_unit_end"] = float(unit.seconds[-1] - a["end_seconds"])
        self.memory_traces.append({
            "unit": int(unit.index),
            "memory_tokens_at_unit_start": int(self.n_events),
            "commits": int(self._unit_commits),
            "window_references_built": int(self._unit_window_refs),
            "references": [{k: v for k, v in a.items() if k != "weight_sum"} for a in refs],
            "memory_digest_after": [{"track": int(s.get("track", -1)), "count": int(s.get("count", 0)),
                                     "t_seconds": float(s.get("t_seconds", 0.0)), "unit": int(s.get("unit", -1))}
                                    for s in (st.get("memory_digest") or [])],
            "note": "weights are the mean attention of the memory head over the frozen window references "
                    "that were actually committed (hypotheses excluded)",
        })
        pool = [chosen] + [x for x in alternatives]
        totals = np.array([float(x.total) for x in pool])
        tau = self.objective.selection_temperature(unit.mean_openness)
        z = -(totals - totals.min()) / max(tau, 1e-12)
        wsel = np.exp(z - z.max())
        wsel = wsel / wsel.sum()
        order_w = np.argsort(-wsel)[:8]
        self.weight_traces.append({
            "unit": int(unit.index), "selection_temperature": float(tau),
            "entries": [{"candidate_id": int(pool[int(k)].candidate.id),
                         "target_id": pool[int(k)].target.id,
                         "total": float(totals[int(k)]), "softmax_weight": float(wsel[int(k)]),
                         "chosen": bool(int(k) == 0)} for k in order_w]})
        self.unit_traces.append({
            "unit": int(unit.index), "warm_start_target": chosen.target.id,
            "normalized_mode_error": float(chosen.normalized_mode_error),
            "memory_tokens_at_unit_start": int(self.n_events),
            "commits": int(self._unit_commits),
            "window_references_built": int(self._unit_window_refs),
            "bound_usage_rate_window_references": (float(self._unit_bound_clipped) / float(self._unit_bound_steps)
                                                   if self._unit_bound_steps else 0.0),
            "reference_order_after": order,
            "probe_gains": self.probe_gains,
            "window_reference_history_effect": self._win_probe,
            "within_unit_reference_feedback": "removed (audit B5/C4/D3.3): the reference never moves "
                                              "while the trajectory is scored against it",
        })

    # ================================================================== signature / trace
    def signature(self) -> np.ndarray:
        parts = [np.asarray(self.A_ema[h], dtype=np.float64).ravel() for h in self.heads]
        parts.append(np.array([float(self.n_events)]))
        parts.append(np.asarray(self.mu_det_mean, dtype=np.float64))
        return np.concatenate(parts)

    def trace(self) -> Dict[str, Any]:
        return {
            "token_definition": {
                "queries": "M track tokens at the current row (track 0 = goal), feature f_i(t)",
                "keys_values": "goal token (xi_G - xi_current), material probes (nu_p), committed memory "
                               "events (dxi) + bounded per-track long-term digest",
                "probe_gains": "foreground %.3f / background %.3f" % (self.fg_gain, self.bg_gain),
                "heads": list(self.heads),
                "coefficients": {"alpha": {h: self.alpha[h] for h in self.heads},
                                 "sign": {h: self.sign[h] for h in self.heads},
                                 "alpha_G": self.alpha_G, "sigma_F": self.sigma_F,
                                 "tau_H_seconds": self.tau_H, "bias_scale": self.bias_scale,
                                 "noise_scale": self.noise_scale, "cov_diag_floor": self.cov_sd ** 2,
                                 "tendency_gain": self.tendency_gain, "excursion_radius": self.excursion},
                "memory_digest_slots": int(self.digest_slots),
                "ignored_parameters": list(self.ignored_parameters),
            },
            "reference_policy": {
                "unit": "propose(): full-unit path from the unit-start probe, warm start only",
                "window": "prepare_reference(): restarted from the realized current composition, model-step "
                          "autoregression over the window rows, committed history only; frozen by the engine",
                "adaptation": "observe_committed() only (attention EMA, reference order, memory digest); "
                              "update() is not implemented and is never called",
                "hypotheses": "future states stay inside the proposal; the mode never writes history.events",
            },
            "time_scale": self._time_scale(),
            "attention_summary": self.attention_traces,
            "memory_references": self.memory_traces,
            "commit_steps": self.step_traces,
            "candidate_weights": self.weight_traces,
            "warnings": list(self.warnings),
            "units": self.unit_traces,
        }
